@startuml
title OAuth 2.0 - Authorization code grant

box "Client side" #MistyRose
    actor "Resource owner" as owner
    participant "User agent" as agent
end box

box "Server side" #LightCyan
    participant Client as client
    participant "AuthZ server" as auth
    participant "Resource server" as resource
end box

activate owner

owner -> agent: Request
activate agent

agent -> client: Request
activate client

client -> client: want to use \n resources
agent <- client: Redirect to \nAuthZ server
deactivate client

==: start OAuth grant :==

agent -> auth: Authorization request
activate auth
note right
    GET /oauth/authorize
end note

note over auth
    Do form authentication
end note

agent <- auth: Present approval form
deactivate auth

owner <- agent: Present approval form
deactivate agent

owner -> agent: Approval
activate agent

agent -> auth: POST approval
activate auth
note right
    POST /oauth/approval
end note

agent <- auth: Redirect to callback
deactivate auth

agent -> client: Notify authorization code
activate client
note right
    GET /callback?code=<AUTHORIZATION CODE>
end note

client -> auth: Request access token
activate auth
note right
    POST /oauth/token
end note

client <- auth: Response access token
deactivate auth


==: end OAuth grant :==

client -> resource: Request resource
activate resource
note right
    GET /foo
    Authorization: Bearer access-token
end note

client <- resource: Response resource
deactivate resource

agent <- client: Response
deactivate client

owner <- agent: Response
deactivate agent
deactivate owner

@enduml