@startuml
title OAuth 2.0 - client credentials grant

actor "Resource owner" as owner
participant Client as client
participant "AuthZ server" as auth
participant "Resource server" as resource

activate owner
owner -> client: Request
activate client

client -> client: want to use \n resources

==: start OAuth grant :==

client -> auth: Request access token
note right
    POST /ouauth token
    Authorization: Basic(clientId, clientSecret)
end note

activate auth
client <- auth: Response access token
deactivate auth

==: end OAuth grant :==

client -> resource: Request resource
activate resource
note right
    GET /foo
    Authorization: Bearer access-token
end note

client <- resource: Response resource
deactivate resource

owner <- client: Response
deactivate client
@enduml
