@startuml
title OAuth 2.0 - resource owner password grant

box "Client side" #MistyRose
    actor "Resource owner" as owner
    participant Client as client
end box

box "Server side" #LightCyan
    participant "AuthZ server" as auth
    participant "Resource server" as resource
end box

activate owner
owner -> client: Request

activate client
client -> client: want to use \n resources

==: start OAuth grant :==

client -> auth: Request access token
activate auth
note right
    POST /oauth/token
    Authorization: Basic(clientId, clientSecret)

    username=<USERNAME>&password=<PASSWORD>
end note

client <- auth: Response access token
deactivate auth

==: end OAuth grant :==

client -> resource: Request resource
activate resource
note right
    GET /foo
    Authorization: Bearer access-token
end note

client <- resource: Response resource
deactivate resource

owner <- client: Response
deactivate client
deactivate owner

@enduml